### ISSUE TITLE
如何更改black_swan主题的导航栏颜色

### ISSUE THREAD

**Issue by crissallan** [greyli/bluelog#31]
我有尝试更改对应的min.css中的background_color 但是好像没有用

**Comment by greyli** [comment]
导航栏颜色可以直接使用 Bootstrap 预置的 bg-* 样式类控制，目前代码里用的是 bg-primary。如果预置的样式类满足不了需求，那就自己定义一个样式类来控制，比如创建一个 bg-custom 类，在你的项目 CSS 文件里类似这样定义它：

```css
.bg-custom{
    background-color: #00bc8c !important;
}
```
